// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportsStats.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace SportsStats.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422115519_TournamentRulesInTournametToNullable")]
    partial class TournamentRulesInTournametToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportsStats.Domain.Matches.Goals.GoalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirstAssistId")
                        .HasColumnType("integer");

                    b.Property<int>("GoalScorerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWinning")
                        .HasColumnType("boolean");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("NetType")
                        .HasColumnType("integer");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("ScoringTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondAssistId")
                        .HasColumnType("integer");

                    b.Property<int?>("StrengthType")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("GoalEvent");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("AwayTeamRoster")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("AwayTeamScore")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamWinType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("HomeTeamRoster")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HomeTeamScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamWinType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SportsStats.Domain.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoMime")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Citizenship", "SportsStats.Domain.Players.Player.Citizenship#Citizenship", b1 =>
                        {
                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CitizenshipName");

                            b1.Property<byte[]>("Photo")
                                .HasColumnType("bytea")
                                .HasColumnName("CitizenshipPhoto");

                            b1.Property<string>("PhotoMime")
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Number", "SportsStats.Domain.Players.Player.Number#PlayerNumber", b1 =>
                        {
                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("Number");
                        });

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SportsStats.Domain.Statistics.TeamStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("OTLosses")
                        .HasColumnType("integer");

                    b.Property<int>("OTWins")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RegularLosses")
                        .HasColumnType("integer");

                    b.Property<int>("RegularWins")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamsStats");
                });

            modelBuilder.Entity("SportsStats.Domain.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoMime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SportsStats.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoMime")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamsId")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Goals.GoalEvent", b =>
                {
                    b.HasOne("SportsStats.Domain.Matches.Match", null)
                        .WithMany("Goals")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Match", b =>
                {
                    b.OwnsOne("SportsStats.Domain.Tournaments.Rules.TournamentRules", "Rules", b1 =>
                        {
                            b1.Property<int>("MatchId");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1
                                .ToJson("Rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");

                            b1.OwnsOne("MatchPointsRules", "MatchPointsRules", b2 =>
                                {
                                    b2.Property<int>("TournamentRulesMatchId");

                                    b2.Property<int?>("DrawPoints");

                                    b2.Property<int>("LossPoints");

                                    b2.Property<int?>("OTLossPoints");

                                    b2.Property<int?>("OTWinPoints");

                                    b2.Property<int?>("ShootoutLossPoints");

                                    b2.Property<int?>("ShootoutWinPoints");

                                    b2.Property<int>("WinPoints");

                                    b2.HasKey("TournamentRulesMatchId");

                                    b2.ToTable("Matches");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentRulesMatchId");
                                });

                            b1.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchRosterRules", "MatchRosterRules", b2 =>
                                {
                                    b2.Property<int>("TournamentRulesMatchId");

                                    b2.Property<int>("MaxDefensemans");

                                    b2.Property<int>("MaxForwards");

                                    b2.Property<int>("MaxGoalies");

                                    b2.Property<int>("MaxPlayers");

                                    b2.Property<int>("MinDefensemans");

                                    b2.Property<int>("MinForwards");

                                    b2.Property<int>("MinGoalies");

                                    b2.Property<int>("MinPlayers");

                                    b2.HasKey("TournamentRulesMatchId");

                                    b2.ToTable("Matches");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentRulesMatchId");
                                });

                            b1.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchTime.MatchTimeRules", "MatchTimeRules", b2 =>
                                {
                                    b2.Property<int>("TournamentRulesMatchId");

                                    b2.Property<bool>("HasOvertime");

                                    b2.Property<bool>("HasShootout");

                                    b2.Property<bool>("IsDrawPossible");

                                    b2.Property<int>("PeriodDurationSeconds");

                                    b2.Property<int>("PeriodsCount");

                                    b2.HasKey("TournamentRulesMatchId");

                                    b2.ToTable("Matches");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentRulesMatchId");

                                    b2.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchTime.MatchOvertimeRules", "OvertimeRules", b3 =>
                                        {
                                            b3.Property<int>("MatchTimeRulesTournamentRulesMatchId");

                                            b3.Property<bool>("GoalEndsOvertime");

                                            b3.Property<int?>("OvertimeDurationSeconds");

                                            b3.Property<int?>("OvertimesCount");

                                            b3.HasKey("MatchTimeRulesTournamentRulesMatchId");

                                            b3.ToTable("Matches");

                                            b3.WithOwner()
                                                .HasForeignKey("MatchTimeRulesTournamentRulesMatchId");
                                        });

                                    b2.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchTime.MatchShootoutRules", "ShootoutRules", b3 =>
                                        {
                                            b3.Property<int>("MatchTimeRulesTournamentRulesMatchId");

                                            b3.HasKey("MatchTimeRulesTournamentRulesMatchId");

                                            b3.ToTable("Matches");

                                            b3.WithOwner()
                                                .HasForeignKey("MatchTimeRulesTournamentRulesMatchId");
                                        });

                                    b2.Navigation("OvertimeRules");

                                    b2.Navigation("ShootoutRules");
                                });

                            b1.Navigation("MatchPointsRules")
                                .IsRequired();

                            b1.Navigation("MatchRosterRules")
                                .IsRequired();

                            b1.Navigation("MatchTimeRules")
                                .IsRequired();
                        });

                    b.Navigation("Rules")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStats.Domain.Tournaments.Tournament", b =>
                {
                    b.OwnsOne("SportsStats.Domain.Tournaments.Rules.TournamentRules", "TournamentRules", b1 =>
                        {
                            b1.Property<int>("TournamentId");

                            b1.HasKey("TournamentId");

                            b1.ToTable("Tournaments");

                            b1
                                .ToJson("TournamentRules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TournamentId");

                            b1.OwnsOne("MatchPointsRules", "MatchPointsRules", b2 =>
                                {
                                    b2.Property<int>("TournamentRulesTournamentId");

                                    b2.Property<int?>("DrawPoints");

                                    b2.Property<int>("LossPoints");

                                    b2.Property<int?>("OTLossPoints");

                                    b2.Property<int?>("OTWinPoints");

                                    b2.Property<int?>("ShootoutLossPoints");

                                    b2.Property<int?>("ShootoutWinPoints");

                                    b2.Property<int>("WinPoints");

                                    b2.HasKey("TournamentRulesTournamentId");

                                    b2.ToTable("Tournaments");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentRulesTournamentId");
                                });

                            b1.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchRosterRules", "MatchRosterRules", b2 =>
                                {
                                    b2.Property<int>("TournamentRulesTournamentId");

                                    b2.Property<int>("MaxDefensemans");

                                    b2.Property<int>("MaxForwards");

                                    b2.Property<int>("MaxGoalies");

                                    b2.Property<int>("MaxPlayers");

                                    b2.Property<int>("MinDefensemans");

                                    b2.Property<int>("MinForwards");

                                    b2.Property<int>("MinGoalies");

                                    b2.Property<int>("MinPlayers");

                                    b2.HasKey("TournamentRulesTournamentId");

                                    b2.ToTable("Tournaments");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentRulesTournamentId");
                                });

                            b1.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchTime.MatchTimeRules", "MatchTimeRules", b2 =>
                                {
                                    b2.Property<int>("TournamentRulesTournamentId");

                                    b2.Property<bool>("HasOvertime");

                                    b2.Property<bool>("HasShootout");

                                    b2.Property<bool>("IsDrawPossible");

                                    b2.Property<int>("PeriodDurationSeconds");

                                    b2.Property<int>("PeriodsCount");

                                    b2.HasKey("TournamentRulesTournamentId");

                                    b2.ToTable("Tournaments");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentRulesTournamentId");

                                    b2.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchTime.MatchOvertimeRules", "OvertimeRules", b3 =>
                                        {
                                            b3.Property<int>("MatchTimeRulesTournamentRulesTournamentId");

                                            b3.Property<bool>("GoalEndsOvertime");

                                            b3.Property<int?>("OvertimeDurationSeconds");

                                            b3.Property<int?>("OvertimesCount");

                                            b3.HasKey("MatchTimeRulesTournamentRulesTournamentId");

                                            b3.ToTable("Tournaments");

                                            b3.WithOwner()
                                                .HasForeignKey("MatchTimeRulesTournamentRulesTournamentId");
                                        });

                                    b2.OwnsOne("SportsStats.Domain.Tournaments.Rules.MatchTime.MatchShootoutRules", "ShootoutRules", b3 =>
                                        {
                                            b3.Property<int>("MatchTimeRulesTournamentRulesTournamentId");

                                            b3.HasKey("MatchTimeRulesTournamentRulesTournamentId");

                                            b3.ToTable("Tournaments");

                                            b3.WithOwner()
                                                .HasForeignKey("MatchTimeRulesTournamentRulesTournamentId");
                                        });

                                    b2.Navigation("OvertimeRules");

                                    b2.Navigation("ShootoutRules");
                                });

                            b1.Navigation("MatchPointsRules")
                                .IsRequired();

                            b1.Navigation("MatchRosterRules")
                                .IsRequired();

                            b1.Navigation("MatchTimeRules")
                                .IsRequired();
                        });

                    b.Navigation("TournamentRules");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Match", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
