// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportsStats.Domain.Matches;
using SportsStats.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace SportsStats.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706151054_Add Period")]
    partial class AddPeriod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportsStats.Domain.Matches.Goals.GoalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirstAssistId")
                        .HasColumnType("integer");

                    b.Property<int>("GoalScorerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWinning")
                        .HasColumnType("boolean");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("NetType")
                        .HasColumnType("integer");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("ScoringTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondAssistId")
                        .HasColumnType("integer");

                    b.Property<int?>("StrengthType")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("GoalEvent");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("boolean");

                    b.Property<Period>("Period")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SportsStats.Domain.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoMime")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Citizenship", "SportsStats.Domain.Players.Player.Citizenship#Citizenship", b1 =>
                        {
                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CitizenshipName");

                            b1.Property<byte[]>("Photo")
                                .HasColumnType("bytea")
                                .HasColumnName("CitizenshipPhoto");

                            b1.Property<string>("PhotoMime")
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Number", "SportsStats.Domain.Players.Player.Number#PlayerNumber", b1 =>
                        {
                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("Number");
                        });

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SportsStats.Domain.Statistics.TeamStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("OTLosses")
                        .HasColumnType("integer");

                    b.Property<int>("OTWins")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RegularLosses")
                        .HasColumnType("integer");

                    b.Property<int>("RegularWins")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamsStats");
                });

            modelBuilder.Entity("SportsStats.Domain.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoMime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SportsStats.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoMime")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamsId")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TournamentRules")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Goals.GoalEvent", b =>
                {
                    b.HasOne("SportsStats.Domain.Matches.Match", null)
                        .WithMany("Goals")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Match", b =>
                {
                    b.OwnsOne("SportsStats.Domain.Matches.MatchTeam", "AwayTeam", b1 =>
                        {
                            b1.Property<int>("MatchId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("AwayTeamId");

                            b1.Property<string>("Roster")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("AwayTeamRoster");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("AwayTeamScore");

                            b1.Property<int>("WinType")
                                .HasColumnType("integer")
                                .HasColumnName("AwayTeamWinType");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsOne("SportsStats.Domain.Matches.MatchTeam", "HomeTeam", b1 =>
                        {
                            b1.Property<int>("MatchId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("HomeTeamId");

                            b1.Property<string>("Roster")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("HomeTeamRoster");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("HomeTeamScore");

                            b1.Property<int>("WinType")
                                .HasColumnType("integer")
                                .HasColumnName("HomeTeamWinType");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("AwayTeam")
                        .IsRequired();

                    b.Navigation("HomeTeam")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStats.Domain.Matches.Match", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
